# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-01 05:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_file",
                    models.FileField(
                        blank=True,
                        upload_to="attachments/",
                        verbose_name="attachment file",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("mimetype", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DontSendEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_address", models.CharField(max_length=50)),
                ("when_added", models.DateTimeField()),
            ],
            options={
                "verbose_name": "don't send entry",
                "verbose_name_plural": "don't send entries",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_address", models.CharField(max_length=50)),
                ("from_address", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=100)),
                ("message_body", models.TextField()),
                ("when_added", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("1", "high"),
                            ("2", "medium"),
                            ("3", "low"),
                            ("4", "deferred"),
                        ],
                        default="2",
                        max_length=1,
                    ),
                ),
                ("html_body", models.TextField(blank=True)),
                ("ready_to_send", models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_address", models.CharField(db_index=True, max_length=50)),
                ("from_address", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=100)),
                ("message_body", models.TextField()),
                ("when_added", models.DateTimeField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("1", "high"),
                            ("2", "medium"),
                            ("3", "low"),
                            ("4", "deferred"),
                        ],
                        max_length=1,
                    ),
                ),
                ("html_body", models.TextField(blank=True)),
                ("when_attempted", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("1", "success"),
                            ("2", "don't send"),
                            ("3", "failure"),
                        ],
                        max_length=1,
                    ),
                ),
                ("log_message", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="attachment",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mailer.Message"
            ),
        ),
    ]
