# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-12-21 07:21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dontsendentry",
            name="to_address",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="message",
            name="from_address",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="message",
            name="to_address",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="messagelog",
            name="from_address",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="messagelog",
            name="to_address",
            field=models.CharField(db_index=True, max_length=254),
        ),
    ]
