# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-17 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0002_auto_20171221_0721"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="when_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="messagelog",
            name="when_attempted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
